### ISSUE TITLE
月間合計シートの休憩時間考慮(E列)計算時に、以前の値が消えない

### ISSUE THREAD

**Issue by hiroki-kaneko** [baykraft/worktimemgr#1]
これはバグではなく、そのような処理が書かれていないためです。毎回手動でE列を消すのは面倒な為、E3:E33までの範囲を消すような処理をGoogle Apps Script内に実装してください。

**Comment by endoyuki2305** [comment]
このissueからとりかかります。

**Comment by endoyuki2305** [comment]
E列削除処理実装完了
検閲待ち
完了後「Done」に移動

**Comment by hiroki-kaneko** [comment]
@endoyuki2305 修正ありがとうございます。ところで、これは私のミスなのですが、Slack Timeshets-testブックには「月間合計」や、客先別休憩タイムテーブルシートがコピーされていませんでしたね。ごめんなさい。遠藤くんはどのようにコードを修正して、どこで動作確認しましたか？

**Comment by hiroki-kaneko** [comment]
修正分のコードをマージしたので本件はcloseします。
